### ISSUE TITLE
Follow \component links to other source file

### ISSUE THREAD

**Issue by linuxrider** [SQbQxeKd3JHD8/simple_ConTeXt#4]
As my thesis is a rather large and distributed project it would be great to quickly navigate through the different source files.
I'm not sure if this in the scope of simple_ConTeXt and if technically possible.
With the search results of the multi-file search it is possible to go to the corresponding file simply by double click.
Is this reasonable for the \component commands as well?

**Comment by equiva1ence** [comment]
I'm pretty sure I could make `\component ...` link to the right file. Maybe while I'm at it I should look into doing the same for `\input` and similar commands. That would be a fun feature to have.

But I'm afraid I don't understand what kind of thing you would like to have for navigating project files. Is using the sidebar in Sublime Text (perhaps with some extra packages, e.g. SideBarEnhancements) not adequate? If so, why not, in what ways is it lacking?

**Comment by SQbQxeKd3JHD8** [comment]
Pickup up this issue again, been a while. So, I have since implemented this feature, you can check out the [file links](https://github.com/SQbQxeKd3JHD8/simple_ConTeXt#file-links) section of the README for some explanation. I'm closing this issue as I believe that concludes things, please re-open if you think this is in error.
